name: test-testdata

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-testdata:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

    - uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: testdata/package-lock.json

    - run: npm ci
      working-directory: testdata

    - name: check repository is not dirty
      run: "[[ -z $(git status --porcelain) ]]"

    - name: show diff
      if: ${{ failure() }}
      run: git status --porcelain
